name: build CAAA deb

on:
  push:
    branches:
      - 'master'
jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - run: sudo apt-get install -y build-essential cmake

      - run: mkdir -p lib
      - run: https://github.com/cktan/tomlc99.git
        working-directory: ./lib
      - run: make && make install
        working-directory: ./lib/tomlc99

      - run: mkdir -p build
      - run: cmake ..
        working-directory: ./build

      - run: cmake --build .
        working-directory: ./build

      - run: cpack -G DEB
        working-directory: ./build

      - uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: 1.0
          artifacts: build/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - run: sudo apt-get install -y build-essential cmake

      - run: mkdir -p lib
      - run: https://github.com/cktan/tomlc99.git
        working-directory: ./lib
      - run: make && make install
        working-directory: ./lib/tomlc99

      - run: mkdir -p build
      - run: cmake ..
        working-directory: ./build

      - run: make
        working-directory: ./build

      - run: make test
        working-directory: ./build
